### ISSUE TITLE
error open with adobe reader

### ISSUE THREAD

**Issue by thachtho** [vbuch/node-signpdf#248]
i got this error after opening a pdf file generated from the example in javascript.js. Help me.
![pdf](https://github.com/vbuch/node-signpdf/assets/32299352/18e0f595-5445-47da-ab1a-b406e92d9147)

**Comment by vbuch** [comment]
Read the details that you are sharing please. It says the document has not been altered since signed which is what you need. It also says that you do not trust the signer. I believe you shouldn't trust any document that some random library on the internet has signed. If you are sure that our self-signed certificate is trustworthy, please go on and add it to you store. Thos way Adobe will know we are a truster authority.
