### ISSUE TITLE
[Feature] Support signing pdf which uses Cross-reference streams 

### ISSUE THREAD

**Issue by kevin8479** [vbuch/node-signpdf#33]
Hi Valery--I ran into a problem signing pdf which contains Cross-reference streams.  Beginning with PDF 1.5, cross-reference information may be stored in a cross-reference stream instead of in a cross-reference table:

... objects ...
12 0 obj % Cross-reference stream
<< /Type /XRef % Cross-reference stream dictionary
/Size ...
/Root ...
>>
stream
... % Stream data containing cross-reference information
endstream
endobj
... more objects ...
startxref
byte_offset_of_cross-reference_stream % Points to object 12
%%EOF

(http://benno.id.au/refs/PDFReference15_v5.pdf)
(https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf)

As it turns out google docs download pdfs in 1.5 format with compressed cross-reference stream, for example:
3 0 obj
<< /Type /XRef /Length 50 /Filter /FlateDecode /DecodeParms << /Columns 4 /Predictor 12 >> /W [ 1 2 1 ] /Index [ 2 15 ] /Info 11 0 R /Root 4 0 R /Size 17 /Prev 17269                 /ID [<731c6cc871d74233cb9a7240c2f04753><731c6cc871d74233cb9a7240c2f04753>] >>
stream
xœcbdàg`b`8	$˜–‚XF@‚±DÜ‰@Â* $›ÆÀÄ¸ÿ9H	#6 ƒ0
endstream
endobj

Let me know if you think you might have time to implement.

**Comment by vbuch** [comment]
No time. Im now reading this on a mobile so cant even see much detail. But it should be generally the same. Well, probably referencing is different. Hope sone time frees up in the weekend and i can have a look. Cant promise thou.

**Comment by kevin8479** [comment]
Thank you very Much for responding!  I am looking too, but, when I say "looking" I mean doing a lot of reading about pdf spec:)  
BTW, your code is really clean - nice job!  Pdf signing still seems to be a bit of hidden art.

**Comment by vbuch** [comment]
Maybe it is wise to get rid of the custom parsing of the PDF and use something that is already available. Without researching at all I would guess that mozilla/pdf.js would have the utilities needed for the task of understanding a PDF's contents.

**Comment by kevin8479** [comment]
Yeah, it is a good point, I was actually wondering the the same thing.

**Comment by vbuch** [comment]
Here again (as in other issues) I would recommend you drop an eye on pdf-lib. Seems promising and might already have what you need to add the placeholder. The actual signing does not care where the placeholder is. If you manage to add it, the signing part of the code will just use it.

**Comment by vbuch** [comment]
@kevin8479 see this comment from the author of pdf-lib: https://github.com/Hopding/pdf-lib/issues/39#issuecomment-432030757

**Comment by therpobinski** [comment]
Hi, I have been working with this library and trying to contribute, but I found this problem, I have a PDF with all its content in `FlateDecode`, this content does not have `Type Catalog` and I think there are several other things of the PDF structure does not exist either, since adding a placeholder causes a problem.
My concern is knowing if creating my own placeholder with `pdf-lib` as I have been trying to do [here](https://github.com/vbuch/node-signpdf/issues/39#issuecomment-554559233) would solve the problem or should I do some decoding?

This is the content of the PDF:

`%����1.6
<</Filter/FlateDecode/First 4/Length 216/N 1/Type/ObjStm>>stream
h�<�QK�0���}[��ޤ$:�i�2Ž�%Kn5�6�&�?�V��s���V�z��{���OSOC���C�3����LN�H��us4]��޽E�\`KGG�}Y�7�~"��#JlP2��i�Q,���Ɔ�Ϣ���+�q���W�����0�L0d��3����1�lh��:�r���AV8Y��`�i��^\�T\{=|@��@���z�-�|�P�
<</Filter/FlateDecode/First 4/Length 49/N 1/Type/ObjStm>>stream
h޲P0P���w�/�+Q0���L)�64
��T��$������
            �
<</Filter/FlateDecode/First 9/Length 42/N 2/Type/ObjStm>>stream
�b��"��.vv�7���+�-�q
<</Filter/FlateDecode/First 5/Length 120/N 1/Type/ObjStm>>stream
h�24R0P���w��+I�+)V02
�;�8�WDf�F
�F����)����E@�
`}A����Eɩ�@3��SK��\��CR+Jb����KKR
                                 �C*
                                    R�z�S��
                                           ؠ'�
<</Length 3525/Subtype/XML/Type/Metadata>>stream
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.4-c005 78.147326, 2012/08/23-13:03:03        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:pdf="http://ns.adobe.com/pdf/1.3/"
            xmlns:xmp="http://ns.adobe.com/xap/1.0/"
            xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
            xmlns:dc="http://purl.org/dc/elements/1.1/">
         <pdf:Producer>Acrobat Distiller 6.0 (Windows)</pdf:Producer>
         <xmp:CreateDate>2006-03-06T15:06:33-05:00</xmp:CreateDate>
         <xmp:CreatorTool>AdobePS5.dll Version 5.2.2</xmp:CreatorTool>
         <xmp:ModifyDate>2016-07-15T10:12:21+08:00</xmp:ModifyDate>
         <xmp:MetadataDate>2016-07-15T10:12:21+08:00</xmp:MetadataDate>
         <xmpMM:DocumentID>uuid:ff3dcfd1-23fa-476f-839a-3e5cae2da2eb</xmpMM:DocumentID>
         <xmpMM:InstanceID>uuid:359350b3-af40-4d8a-9d6c-03186b4ffb36</xmpMM:InstanceID>
         <dc:format>application/pdf</dc:format>
         <dc:title>
            <rdf:Alt>
               <rdf:li xml:lang="x-default">Blank PDF Document</rdf:li>
            </rdf:Alt>
         </dc:title>
         <dc:creator>
            <rdf:Seq>
               <rdf:li>Department of Justice (Executive Office of Immigration Review)</rdf:li>
            </rdf:Seq>
         </dc:creator>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                           
<?xpacket end="w"?>
<</Filter/FlateDecode/Length 10>>streams 8 0 R/Type/Catalog>>
H0
<</DecodeParms<</Columns 4/Predictor 12>>/Filter/FlateDecode/ID[<DB7775CCE227F6B30C440DF4221DC390><BFCCCF3F57F6134ABD3C04A9E4CA106E>]/Info 9 0 R/Length 80/Root 11 0 R/Size 29/Type/XRef/W[1 2 1]>>stream
h�bb&0��l�����y(L01H�Y�@������P��3�x�}���Qp"���H0����@�v ���`�
startxref
4576
%%EOF`
