### ISSUE TITLE
Not working on Edge

### ISSUE THREAD

**Issue by mfespuch** [vbuch/node-signpdf#66]
Hello! Thank you for the project first of all.

I have a problem running this library in Microsoft Edge, when I run my project shows an error in console at the beginning.

![Screenshot_1](https://user-images.githubusercontent.com/32874266/77743832-f2028980-7018-11ea-9672-6aeeaf1647f3.jpg)

When debug I see the error here:

![Screenshot_2](https://user-images.githubusercontent.com/32874266/77744126-6fc69500-7019-11ea-9a91-7c8d28e9ae01.jpg)

Do you know something about that?

Thank you for your help!

**Comment by mfespuch** [comment]
I noticed that the problem is with the spread operator, if all spreads operators change into Object.assign is working.

I am with an angular application, I don't know if is possible to when is compiling the app all spreads operators change into Object.assign...

**Comment by vbuch** [comment]
As you can see from the name of the project, it was initially done in node. I personally never tested it in a browser. I am surprised that's the only limitation in a browser. Yiu could make a PR to configure babel's building for browsers and node. See https://babeljs.io/docs/en/babel-preset-env#targetsbrowsers
I never planned to make it work for browser, but since [pdfsign.js points this way](https://github.com/vbuch/node-signpdf/issues/62), the time may have come to do that. Again, a PR would be appreciated.
